cars:
  count: 200
  arrival_time_min: 1ms   # new car arrives every 1-2ms
  arrival_time_max: 2ms
stations:
  gas:
    count: 2
    serve_time_min: 20ms
    serve_time_max: 50ms
  diesel:
    count: 2
    serve_time_min: 30ms
    serve_time_max: 60ms
  lpg:
    count: 1
    serve_time_min: 40ms
    serve_time_max: 70ms
  electric:
    count: 1
    serve_time_min: 50ms
    serve_time_max: 100ms
registers:
   count: 2
   handle_time_min: 10ms
   handle_time_max: 30ms
